In [18]:
import pandas as pd

In [19]:
orders = pd.read_csv("Documents/Orders.csv", skiprows=1)

In [20]:
orders.head()

,Sales Record Number,Order Number,Buyer Username,Buyer Name,Buyer Email,Buyer Note,Buyer Address 1,Buyer Address 2,Buyer City,Buyer State,...,Authenticity Verification Status,Authenticity Verification Outcome Reason,PSA Vault Program,Vault Fulfillment Type,eBay Fulfillment Program,Tax City,Tax State,Tax Zip,Tax Country,eBay International Shipping
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,507,13-14439-25147,ma385741,Mark Neal,0116466e8359a6bb9fac@members.ebay.com,NaN,Po Box 5302,NaN,Santa Maria,CA,...,NaN,NaN,No,NaN,No,Santa Maria,CA,93456-5302,United States,No
2,506,12-14440-08413,fyr-fytr3814,Brett Mullins,01164378d136967c826d@members.ebay.com,NaN,412 McNeil Mill Rd.,NaN,Rocky Mount,VA,...,NaN,NaN,No,NaN,No,Rocky Mount,VA,24151-3519,United States,No
3,503,21-14417-16985,alkro39,Alex Kroczek,0116193980e2922a9a7f@members.ebay.com,NaN,105 Rainbow Trl,NaN,Michigan City,IN,...,NaN,NaN,No,NaN,No,Michigan City,IN,46360-5725,United States,No
4,505,08-14436-02594,jesus250,Jesus lopez,01160ef78e75bb196b25@members.ebay.com,NaN,515 Jewett Ave,Fl 2,Staten Island,NY,...,NaN,NaN,No,NaN,No,Staten Island,NY,10302-2615,United States,No

In [21]:
orders = orders[orders["Sales Record Number"].notna()].copy()

In [22]:
print(f"ORDERS COLUMNS:\n{orders.columns.tolist()}")

ORDERS COLUMNS:
['Sales Record Number', 'Order Number', 'Buyer Username', 'Buyer Name', 'Buyer Email', 'Buyer Note', 'Buyer Address 1', 'Buyer Address 2', 'Buyer City', 'Buyer State', 'Buyer Zip', 'Buyer Country', 'Buyer Tax Identifier Name', 'Buyer Tax Identifier Value', 'Ship To Name', 'Ship To Phone', 'Ship To Address 1', 'Ship To Address 2', 'Ship To City', 'Ship To State', 'Ship To Zip', 'Ship To Country', 'Item Number', 'Item Title', 'Custom Label', 'Sold Via Promoted Listings', 'Quantity', 'Sold For', 'Shipping And Handling', 'Item Location', 'Item Zip Code', 'Item Country', 'eBay Collect And Remit Tax Rate', 'eBay Collect And Remit Tax Type', 'eBay Reference Name', 'eBay Reference Value', 'Tax Status', 'Seller Collected Tax', 'eBay Collected Tax', 'Electronic Waste Recycling Fee', 'Mattress Recycling Fee', 'Battery Recycling Fee', 'White Goods Disposal Tax', 'Tire Recycling Fee', 'Additional Fee', 'Lumber Fee', 'Prepaid Wireless Fee', 'Road Improvement And Food Delivery Fee', 'eBay Collected Charges', 'Total Price', 'eBay Collected Tax and Fees Included in Total', 'Payment Method', 'Sale Date', 'Paid On Date', 'Ship By Date', 'Minimum Estimated Delivery Date', 'Maximum Estimated Delivery Date', 'Shipped On Date', 'Feedback Left', 'Feedback Received', 'My Item Note', 'PayPal Transaction ID', 'Shipping Service', 'Tracking Number', 'Transaction ID', 'Variation Details', 'Global Shipping Program', 'Global Shipping Reference ID', 'Click And Collect', 'Click And Collect Reference Number', 'eBay Plus', 'Authenticity Verification Program', 'Authenticity Verification Status', 'Authenticity Verification Outcome Reason', 'PSA Vault Program', 'Vault Fulfillment Type', 'eBay Fulfillment Program', 'Tax City', 'Tax State', 'Tax Zip', 'Tax Country', 'eBay International Shipping']

In [23]:
with open("Documents/financials.csv", "r", encoding="utf-8") as f:
    for i in range(10):
        print(i, f.readline())

0 ﻿,,,,,,,,,,,,,,

1 Disclaimers

2 • This is an analytics report and currently we support downloading top 8000 listings by sold quantity.

3 • This report ONLY includes listings sold within the selected time range. Any fees charged or credits applied to listings sold outside this time range are not included in this report. These fees and credits are included in the selling costs number shown on the Seller Hub Performance sales report dashboard.

4 • Any fees charged or credits applied to these listings outside this time range are not included in this report.

5 "• For the orders that have more than one unique item (multi-item orders), the order level fees/costs are distributed in individual items as follows. Total shipping label cost and per order fixed final value fees are equally distributed to each item."

6

7 "Report for Mar 3, 2026 to Apr 2, 2026"

8 Listing title,eBay item ID,Store category L1,Store category L2,Quantity sold,Total sales (Includes taxes),Item sales,Taxes and government fees paid by buyer to you,Taxes and government fees paid by buyer to eBay,Shipping and handling paid by buyer to you,Total selling costs,Insertion fees,Optional listing upgrade fees,Final value fees,Promoted Listings - General fees,Promoted Listings - Priority fees,Ads Express fees,Promoted Offsite - Fees,Other eBay fees,Deposit processing fees,Fee credits,Shipping labels cost (Amount you paid to buy shipping labels on eBay),Net sales (Net of taxes and selling costs),Average Selling price,Quantity sold via promoted listing,Quantity sold via Best Offers,Quantity sold via Seller Initiated Offers,

9 Craftsman 40811 40804 Steel Brass Thickness Feeler Gauge Set,388869921405,-,-,1,$21.75,$15.76,$0.00,$1.65,$4.34,$5.96,$0.00,$0.00,$4.15,$3.31,$0.00,$0.00,$0.00,$0.00,$0.00,$1.50,$0.00,$14.14,$21.75,1,0,0

In [24]:
financials = pd.read_csv("Documents/financials.csv", skiprows=8)
financials.head()

,Listing title,eBay item ID,Store category L1,Store category L2,Quantity sold,Total sales (Includes taxes),Item sales,Taxes and government fees paid by buyer to you,Taxes and government fees paid by buyer to eBay,Shipping and handling paid by buyer to you,...,Other eBay fees,Deposit processing fees,Fee credits,Shipping labels cost (Amount you paid to buy shipping labels on eBay),Net sales (Net of taxes and selling costs),Average Selling price,Quantity sold via promoted listing,Quantity sold via Best Offers,Quantity sold via Seller Initiated Offers,Unnamed: 27
0,Craftsman 40811 40804 Steel Brass Thickness Fe...,388869921405,-,-,1,$21.75,$15.76,$0.00,$1.65,$4.34,...,$0.00,$0.00,$1.50,$0.00,$14.14,$21.75,1,0,0,NaN
1,Proto Blade Step Cut Feeler Gauge Set 000N,388869925564,-,-,1,$14.40,$9.34,$0.00,$1.10,$3.96,...,$0.00,$0.00,$1.45,$0.00,$9.22,$14.40,1,0,0,NaN
2,Craftsman Rally Torx 41473m Screwdriver Vintag...,388931444187,-,-,1,$19.42,$10.00,$0.00,$0.70,$8.72,...,$0.00,$0.00,$0.00,$5.29,$8.06,$19.42,1,1,0,NaN
3,Vintage Craftsman Lineman’s Pliers – Amber Han...,389064046147,-,-,1,$24.08,$15.00,$0.00,$0.98,$8.10,...,$0.00,$0.00,$0.00,$8.10,$8.68,$24.08,1,1,0,NaN
4,Blackhawk USA Nut Driver Set ST-803 ST-809 ST-...,389237612378,-,-,1,$23.96,$13.99,$0.00,$1.62,$8.35,...,$0.00,$0.00,$0.00,$8.35,$7.93,$23.96,1,0,0,NaN

In [25]:
print(f"FINANCIALS COLUMNS:\n{financials.columns.tolist()}")

FINANCIALS COLUMNS:
['Listing title', 'eBay item ID', 'Store category L1', 'Store category L2', 'Quantity sold', 'Total sales (Includes taxes)', 'Item sales', 'Taxes and government fees paid by buyer to you', 'Taxes and government fees paid by buyer to eBay', 'Shipping and handling paid by buyer to you', 'Total selling costs', 'Insertion fees', 'Optional listing upgrade fees', 'Final value fees', 'Promoted Listings - General fees', 'Promoted Listings - Priority fees', 'Ads Express fees', 'Promoted Offsite - Fees', 'Other eBay fees', 'Deposit processing fees', 'Fee credits', 'Shipping labels cost (Amount you paid to buy shipping labels on eBay)', 'Net sales (Net of taxes and selling costs)', 'Average Selling price', 'Quantity sold via promoted listing', 'Quantity sold via Best Offers', 'Quantity sold via Seller Initiated Offers', 'Unnamed: 27']

In [26]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
        .str.replace("/", "_", regex=False)
        .str.replace("(", "", regex=False)
        .str.replace(")", "", regex=False)
        .str.replace(",", "", regex=False)
    )
    return df

orders = clean_columns(orders)
financials = clean_columns(financials)
orders.head()

,sales_record_number,order_number,buyer_username,buyer_name,buyer_email,buyer_note,buyer_address_1,buyer_address_2,buyer_city,buyer_state,...,authenticity_verification_status,authenticity_verification_outcome_reason,psa_vault_program,vault_fulfillment_type,ebay_fulfillment_program,tax_city,tax_state,tax_zip,tax_country,ebay_international_shipping
1,507,13-14439-25147,ma385741,Mark Neal,0116466e8359a6bb9fac@members.ebay.com,NaN,Po Box 5302,NaN,Santa Maria,CA,...,NaN,NaN,No,NaN,No,Santa Maria,CA,93456-5302,United States,No
2,506,12-14440-08413,fyr-fytr3814,Brett Mullins,01164378d136967c826d@members.ebay.com,NaN,412 McNeil Mill Rd.,NaN,Rocky Mount,VA,...,NaN,NaN,No,NaN,No,Rocky Mount,VA,24151-3519,United States,No
3,503,21-14417-16985,alkro39,Alex Kroczek,0116193980e2922a9a7f@members.ebay.com,NaN,105 Rainbow Trl,NaN,Michigan City,IN,...,NaN,NaN,No,NaN,No,Michigan City,IN,46360-5725,United States,No
4,505,08-14436-02594,jesus250,Jesus lopez,01160ef78e75bb196b25@members.ebay.com,NaN,515 Jewett Ave,Fl 2,Staten Island,NY,...,NaN,NaN,No,NaN,No,Staten Island,NY,10302-2615,United States,No
5,504,24-14427-79252,daes-3822,David Estep,011611f677c121c9a201@members.ebay.com,NaN,1529 Deodate Rd,NaN,Elizabethtown,PA,...,NaN,NaN,No,NaN,No,Elizabethtown,PA,17022-9034,United States,No

In [27]:
orders.head()

,sales_record_number,order_number,buyer_username,buyer_name,buyer_email,buyer_note,buyer_address_1,buyer_address_2,buyer_city,buyer_state,...,authenticity_verification_status,authenticity_verification_outcome_reason,psa_vault_program,vault_fulfillment_type,ebay_fulfillment_program,tax_city,tax_state,tax_zip,tax_country,ebay_international_shipping
1,507,13-14439-25147,ma385741,Mark Neal,0116466e8359a6bb9fac@members.ebay.com,NaN,Po Box 5302,NaN,Santa Maria,CA,...,NaN,NaN,No,NaN,No,Santa Maria,CA,93456-5302,United States,No
2,506,12-14440-08413,fyr-fytr3814,Brett Mullins,01164378d136967c826d@members.ebay.com,NaN,412 McNeil Mill Rd.,NaN,Rocky Mount,VA,...,NaN,NaN,No,NaN,No,Rocky Mount,VA,24151-3519,United States,No
3,503,21-14417-16985,alkro39,Alex Kroczek,0116193980e2922a9a7f@members.ebay.com,NaN,105 Rainbow Trl,NaN,Michigan City,IN,...,NaN,NaN,No,NaN,No,Michigan City,IN,46360-5725,United States,No
4,505,08-14436-02594,jesus250,Jesus lopez,01160ef78e75bb196b25@members.ebay.com,NaN,515 Jewett Ave,Fl 2,Staten Island,NY,...,NaN,NaN,No,NaN,No,Staten Island,NY,10302-2615,United States,No
5,504,24-14427-79252,daes-3822,David Estep,011611f677c121c9a201@members.ebay.com,NaN,1529 Deodate Rd,NaN,Elizabethtown,PA,...,NaN,NaN,No,NaN,No,Elizabethtown,PA,17022-9034,United States,No

In [28]:
orders = orders[
    [
        "sales_record_number",
        "order_number",
        "buyer_username",
        "buyer_city",
        "buyer_state",
        "buyer_zip",
        "item_number",
        "item_title",
        "quantity",
        "sold_for",
        "shipping_and_handling",
        "item_location",
        "item_zip_code",
        "item_country",
        "sold_via_promoted_listings",
        "ebay_collected_tax",
        "total_price",
        "sale_date",
        "paid_on_date",
        "ship_by_date",
        "shipped_on_date",
        "shipping_service",
        "tracking_number",
        "transaction_id"
    ]
].copy()

financials = financials[
    [
        "listing_title",
        "ebay_item_id",
        "quantity_sold",
        "total_sales_includes_taxes",
        "item_sales",
        "taxes_and_government_fees_paid_by_buyer_to_you",
        "taxes_and_government_fees_paid_by_buyer_to_ebay",
        "shipping_and_handling_paid_by_buyer_to_you",
        "total_selling_costs",
        "final_value_fees",
        "promoted_listings___general_fees",
        "shipping_labels_cost_amount_you_paid_to_buy_shipping_labels_on_ebay",
        "net_sales_net_of_taxes_and_selling_costs",
        "average_selling_price",
        "quantity_sold_via_promoted_listing",
        "quantity_sold_via_best_offers",
            ]
].copy()

In [29]:
orders.head()

,sales_record_number,order_number,buyer_username,buyer_city,buyer_state,buyer_zip,item_number,item_title,quantity,sold_for,...,sold_via_promoted_listings,ebay_collected_tax,total_price,sale_date,paid_on_date,ship_by_date,shipped_on_date,shipping_service,tracking_number,transaction_id
1,507,13-14439-25147,ma385741,Santa Maria,CA,93456-5302,3.898173e+11,RadioShack PRO-89 200 Channel Handheld Scanner...,1.0,$31.50,...,Yes,$2.76,$40.77,Mar-31-26,Mar-31-26,Apr-02-26,Apr-01-26,USPS Ground Advantage,9434608106244977750965,1.008206e+13
2,506,12-14440-08413,fyr-fytr3814,Rocky Mount,VA,24151-3519,3.894790e+11,Snap-on F4LA 3/8” Drive Speed Handle Crank Vin...,1.0,$39.99,...,Yes,$2.12,$48.54,Mar-31-26,Mar-31-26,Apr-02-26,Mar-31-26,USPS Ground Advantage,9400108105463824771345,1.008080e+13
3,503,21-14417-16985,alkro39,Michigan City,IN,46360-5725,3.897947e+11,Vintage Tool Lot Craftsman Ratchet Sockets Wre...,1.0,$41.78,...,Yes,$2.92,$79.85,Mar-29-26,Mar-29-26,Mar-31-26,Mar-29-26,USPS Ground Advantage,9434608106244967231375,1.007951e+13
4,505,08-14436-02594,jesus250,Staten Island,NY,10302-2615,3.897801e+11,Stanley Aladdin Lunch Box Cooler w/ Thermos 10...,1.0,$51.00,...,No,$5.70,$69.95,Mar-29-26,Mar-29-26,Mar-31-26,Mar-29-26,USPS Ground Advantage,9434608106245991215201,1.007975e+13
5,504,24-14427-79252,daes-3822,Elizabethtown,PA,17022-9034,3.897835e+11,Vintage Craftsman 66577 Pry Bar USA Green Pati...,1.0,$24.00,...,Yes,$2.00,$35.26,Mar-29-26,Mar-29-26,Mar-31-26,Mar-29-26,USPS Ground Advantage,9434608106245991214327,1.007968e+13

In [30]:
financials.head()

,listing_title,ebay_item_id,quantity_sold,total_sales_includes_taxes,item_sales,taxes_and_government_fees_paid_by_buyer_to_you,taxes_and_government_fees_paid_by_buyer_to_ebay,shipping_and_handling_paid_by_buyer_to_you,total_selling_costs,final_value_fees,promoted_listings___general_fees,shipping_labels_cost_amount_you_paid_to_buy_shipping_labels_on_ebay,net_sales_net_of_taxes_and_selling_costs,average_selling_price,quantity_sold_via_promoted_listing,quantity_sold_via_best_offers
0,Craftsman 40811 40804 Steel Brass Thickness Fe...,388869921405,1,$21.75,$15.76,$0.00,$1.65,$4.34,$5.96,$4.15,$3.31,$0.00,$14.14,$21.75,1,0
1,Proto Blade Step Cut Feeler Gauge Set 000N,388869925564,1,$14.40,$9.34,$0.00,$1.10,$3.96,$4.08,$3.13,$2.40,$0.00,$9.22,$14.40,1,0
2,Craftsman Rally Torx 41473m Screwdriver Vintag...,388931444187,1,$19.42,$10.00,$0.00,$0.70,$8.72,$10.66,$3.04,$2.33,$5.29,$8.06,$19.42,1,1
3,Vintage Craftsman Lineman’s Pliers – Amber Han...,389064046147,1,$24.08,$15.00,$0.00,$0.98,$8.10,$14.42,$3.67,$2.65,$8.10,$8.68,$24.08,1,1
4,Blackhawk USA Nut Driver Set ST-803 ST-809 ST-...,389237612378,1,$23.96,$13.99,$0.00,$1.62,$8.35,$14.41,$3.66,$2.40,$8.35,$7.93,$23.96,1,0

In [31]:
def clean_currency(series):
    return (
        series.astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
        .replace({"": None, "nan": None})
        .astype(float)
    )

In [32]:
orders["sold_for"] = clean_currency(orders["sold_for"])
orders["shipping_and_handling"] = clean_currency(orders["shipping_and_handling"])
orders["ebay_collected_tax"] = clean_currency(orders["ebay_collected_tax"])
orders["total_price"] = clean_currency(orders["total_price"])
money_cols = [
    "total_sales_includes_taxes",
    "item_sales",
    "taxes_and_government_fees_paid_by_buyer_to_you",
    "taxes_and_government_fees_paid_by_buyer_to_ebay",
    "shipping_and_handling_paid_by_buyer_to_you",
    "total_selling_costs",
    "final_value_fees",
    "promoted_listings___general_fees",
    "shipping_labels_cost_amount_you_paid_to_buy_shipping_labels_on_ebay",
    "net_sales_net_of_taxes_and_selling_costs",
    "average_selling_price"
]

for col in money_cols:
    financials[col] = clean_currency(financials[col])

In [33]:
print(orders["sale_date"].head(10))

1     Mar-31-26
2     Mar-31-26
3     Mar-29-26
4     Mar-29-26
5     Mar-29-26
6     Mar-28-26
7     Mar-28-26
8     Mar-28-26
9     Mar-28-26
10    Mar-28-26
Name: sale_date, dtype: object

In [34]:
orders[col] = pd.to_datetime(orders[col], format="%Y-%m-%d", errors="coerce")

KeyError: 'average_selling_price'

In [35]:
date_cols = ["sale_date", "paid_on_date", "ship_by_date", "shipped_on_date"]

for col in date_cols:
    orders[col] = pd.to_datetime(
        orders[col],
        format="YOUR_FORMAT_HERE",
        errors="coerce"
    )

In [36]:
print("Orders shape:", orders.shape)
print("Financials shape:", financials.shape)

print("Duplicate order numbers:", orders["order_number"].duplicated().sum())
print("Duplicate item numbers in financials:", financials["ebay_item_id"].duplicated().sum())

print(orders.isna().sum().sort_values(ascending=False).head(10))
print(financials.isna().sum().sort_values(ascending=False).head(10))

Orders shape: (146, 24)
Financials shape: (33, 16)
Duplicate order numbers: 3
Duplicate item numbers in financials: 0
shipped_on_date     146
ship_by_date        146
paid_on_date        146
sale_date           146
tracking_number       8
buyer_city            5
buyer_state           5
buyer_zip             5
shipping_service      5
item_zip_code         4
dtype: int64
listing_title                                      0
ebay_item_id                                       0
quantity_sold                                      0
total_sales_includes_taxes                         0
item_sales                                         0
taxes_and_government_fees_paid_by_buyer_to_you     0
taxes_and_government_fees_paid_by_buyer_to_ebay    0
shipping_and_handling_paid_by_buyer_to_you         0
total_selling_costs                                0
final_value_fees                                   0
dtype: int64

In [37]:
orders[orders["order_number"].duplicated(keep=False)].sort_values("order_number")

,sales_record_number,order_number,buyer_username,buyer_city,buyer_state,buyer_zip,item_number,item_title,quantity,sold_for,...,sold_via_promoted_listings,ebay_collected_tax,total_price,sale_date,paid_on_date,ship_by_date,shipped_on_date,shipping_service,tracking_number,transaction_id
8,500,26-14404-16793,finkso2,Winnsboro,TX,75494-8577,NaN,NaN,2.0,56.98,...,NaN,5.23,76.4,NaT,NaT,NaT,NaT,USPS Ground Advantage,NaN,NaN
9,500,26-14404-16793,finkso2,NaN,NaN,NaN,3.896535e+11,Estwing 16 oz Steel Claw Hammer USA One-Piece ...,1.0,19.99,...,Yes,NaN,NaN,NaT,NaT,NaT,NaT,NaN,9434608106245988016750,1.007947e+13
10,500,26-14404-16793,finkso2,NaN,NaN,NaN,3.897635e+11,Vintage Craftsman USA Screwdriver Lot Mixed Fl...,1.0,36.99,...,Yes,NaN,NaN,NaT,NaT,NaT,NaT,NaN,9434608106245988016750,1.007947e+13
27,481,NaN,jovaz-7134,NaN,NaN,NaN,3.897534e+11,Vintage Craftsman Ignition Wrench Set Partial ...,1.0,18.00,...,No,0.00,18.0,NaT,NaT,NaT,NaT,NaN,NaN,1.008044e+13
146,Seller ID : jealousmo21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN

In [38]:
print("Duplicate item numbers in orders:", orders["item_number"].duplicated().sum())
orders[orders["item_number"].duplicated(keep=False)].sort_values("item_number")

Duplicate item numbers in orders: 2

,sales_record_number,order_number,buyer_username,buyer_city,buyer_state,buyer_zip,item_number,item_title,quantity,sold_for,...,sold_via_promoted_listings,ebay_collected_tax,total_price,sale_date,paid_on_date,ship_by_date,shipped_on_date,shipping_service,tracking_number,transaction_id
8,500,26-14404-16793,finkso2,Winnsboro,TX,75494-8577,NaN,NaN,2.0,56.98,...,NaN,5.23,76.4,NaT,NaT,NaT,NaT,USPS Ground Advantage,NaN,NaN
145,142,record(s) downloaded,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN
146,Seller ID : jealousmo21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaN,NaN

In [39]:
orders["item_number"] = orders["item_number"].astype(str).str.strip()
financials["ebay_item_id"] = financials["ebay_item_id"].astype(str).str.strip()

orders["matched_in_financials"] = orders["item_number"].isin(financials["ebay_item_id"])

print(orders["matched_in_financials"].value_counts())
print("Match rate:", orders["matched_in_financials"].mean())

matched_in_financials
False    146
Name: count, dtype: int64
Match rate: 0.0

In [40]:
merged = orders.merge(
    financials,
    left_on="item_number",
    right_on="ebay_item_id",
    how="left"
)

print(merged.shape)
print(merged[["order_number", "item_number", "item_title", "listing_title"]].head(10))

(146, 41)
     order_number     item_number  \
0  13-14439-25147  389817347239.0
1  12-14440-08413  389478957836.0
2  21-14417-16985  389794681822.0
3  08-14436-02594  389780133963.0
4  24-14427-79252  389783537611.0
5  05-14436-16665  389783496802.0
6  11-14426-26009  389812836611.0
7  26-14404-16793             nan
8  26-14404-16793  389653454973.0
9  26-14404-16793  389763451911.0

                                          item_title listing_title
0  RadioShack PRO-89 200 Channel Handheld Scanner...           NaN
1  Snap-on F4LA 3/8” Drive Speed Handle Crank Vin...           NaN
2  Vintage Tool Lot Craftsman Ratchet Sockets Wre...           NaN
3  Stanley Aladdin Lunch Box Cooler w/ Thermos 10...           NaN
4  Vintage Craftsman 66577 Pry Bar USA Green Pati...           NaN
5  Arizona License Plate GCA 9P4 Grand Canyon Sta...           NaN
6  Craftsman 94 Pc Mechanics Tool Set SAE Metric ...           NaN
7                                                NaN           NaN
8  Estwing 16 oz Steel Claw Hammer USA One-Piece ...           NaN
9  Vintage Craftsman USA Screwdriver Lot Mixed Fl...           NaN

In [41]:
print(merged["listing_title"].notna().value_counts())
print("Join match rate:", merged["listing_title"].notna().mean())

listing_title
False    146
Name: count, dtype: int64
Join match rate: 0.0

In [42]:
orders[orders["order_number"].duplicated(keep=False)].sort_values("order_number")
print("Duplicate item numbers in orders:", orders["item_number"].duplicated().sum())
orders["item_number"] = orders["item_number"].astype(str).str.strip()
financials["ebay_item_id"] = financials["ebay_item_id"].astype(str).str.strip()

orders["matched_in_financials"] = orders["item_number"].isin(financials["ebay_item_id"])
print(orders["matched_in_financials"].value_counts())
print("Match rate:", orders["matched_in_financials"].mean())
merged = orders.merge(
    financials,
    left_on="item_number",
    right_on="ebay_item_id",
    how="left"
)
print(merged[["order_number", "item_number", "item_title", "listing_title"]].head(10))

Duplicate item numbers in orders: 2
matched_in_financials
False    146
Name: count, dtype: int64
Match rate: 0.0
     order_number     item_number  \
0  13-14439-25147  389817347239.0
1  12-14440-08413  389478957836.0
2  21-14417-16985  389794681822.0
3  08-14436-02594  389780133963.0
4  24-14427-79252  389783537611.0
5  05-14436-16665  389783496802.0
6  11-14426-26009  389812836611.0
7  26-14404-16793             nan
8  26-14404-16793  389653454973.0
9  26-14404-16793  389763451911.0

                                          item_title listing_title
0  RadioShack PRO-89 200 Channel Handheld Scanner...           NaN
1  Snap-on F4LA 3/8” Drive Speed Handle Crank Vin...           NaN
2  Vintage Tool Lot Craftsman Ratchet Sockets Wre...           NaN
3  Stanley Aladdin Lunch Box Cooler w/ Thermos 10...           NaN
4  Vintage Craftsman 66577 Pry Bar USA Green Pati...           NaN
5  Arizona License Plate GCA 9P4 Grand Canyon Sta...           NaN
6  Craftsman 94 Pc Mechanics Tool Set SAE Metric ...           NaN
7                                                NaN           NaN
8  Estwing 16 oz Steel Claw Hammer USA One-Piece ...           NaN
9  Vintage Craftsman USA Screwdriver Lot Mixed Fl...           NaN

In [43]:
## Datasets orders and financials DO NOT join at all due to 0% match rate. Financials is not row-level dataset; it is a summarized report.

In [44]:
## Focusing on only Orders dataset ##

In [45]:
orders.head()
orders.dtypes

sales_record_number                   object
order_number                          object
buyer_username                        object
buyer_city                            object
buyer_state                           object
buyer_zip                             object
item_number                           object
item_title                            object
quantity                             float64
sold_for                             float64
shipping_and_handling                float64
item_location                         object
item_zip_code                        float64
item_country                          object
sold_via_promoted_listings            object
ebay_collected_tax                   float64
total_price                          float64
sale_date                     datetime64[ns]
paid_on_date                  datetime64[ns]
ship_by_date                  datetime64[ns]
shipped_on_date               datetime64[ns]
shipping_service                      object
tracking_number                       object
transaction_id                       float64
matched_in_financials                   bool
dtype: object

In [46]:
orders["gross_revenue"] = orders["sold_for"] + orders["shipping_and_handling"]
orders["sale_month"] = orders["sale_date"].dt.to_period("M").astype(str)

In [47]:
## Sales over time ##
orders.groupby("sale_month")["gross_revenue"].sum()

sale_month
NaT    6812.74
Name: gross_revenue, dtype: float64

In [48]:
## Top items by price
orders.sort_values("sold_for", ascending=False)[
    ["item_title", "sold_for"]
].head(10)

                                            item_title  sold_for
58   Vintage H Gerstner & Sons Dayton Ohio Machinis...    675.00
98   Vintage Mac Tools Red 6-Drawer Side Cabinet To...    350.00
85   Wenger Giant Swiss Army Knife 80+ Functions Pl...    249.99
131  Snap On 1/2 Inch Drive Ratchet S80a   Chrome S...    129.99
115  L&R Ultrasonic Cleaner Model T-11 Vintage Jewe...     90.00
117  Vintage Homelite XL Mini Automatic Type 10112 ...     89.99
17   Vintage Craftsman 391.5195 Woodworking Bench V...     89.99
100  Vintage Gräper USA CHOPPER-1 Mechanical Spring...     80.00
144  Railroad Track Anvil 18 lb Bench Blacksmith Je...     79.99
133  ERTL Vintage 1/22 Scale Diecast Ford 7500 Back...     77.60

In [49]:
## Buyer Location ##
orders.groupby("buyer_state")["gross_revenue"].sum().sort_values(ascending=False)

buyer_state
TX                      840.62
IA                      819.74
CA                      551.51
PA                      420.63
NV                      409.63
NY                      337.38
MO                      303.26
DE                      259.25
IN                      223.38
CO                      210.85
IL                      206.46
WI                      181.92
NC                      167.29
AZ                      145.80
VT                      124.22
MN                      122.31
FL                      118.82
OR                      113.66
OK                      110.45
VA                      100.00
NJ                       94.61
TN                       93.92
MI                       91.26
WA                       87.54
AL                       79.84
UT                       74.07
GA                       60.65
AR                       55.70
NH                       48.28
ND                       43.09
WY                       42.86
KY                       40.23
ID                       40.17
KS                       37.91
HI                       36.85
Auvergne-Rhône-Alpes     32.22
AE                       25.06
OH                       22.34
MT                       20.96
Name: gross_revenue, dtype: float64

In [50]:
## Average Sale Price ##
orders["sold_for"].mean()

np.float64(38.24548611111111)

In [53]:
## Orders vs. Financials Dataset ##
orders["gross_revenue"].sum()

np.float64(6812.74)

In [52]:
financials["total_sales_includes_taxes"].sum()

np.float64(1415.27)

In [54]:
financials["net_sales_net_of_taxes_and_selling_costs"].sum()

np.float64(682.4000000000001)

In [55]:
orders_clean = orders[
    [
        "order_number",
        "sale_date",
        "buyer_state",
        "item_title",
        "sold_for",
        "shipping_and_handling",
        "gross_revenue"
    ]
].copy()

orders_clean.head()

,order_number,sale_date,buyer_state,item_title,sold_for,shipping_and_handling,gross_revenue
1,13-14439-25147,NaT,CA,RadioShack PRO-89 200 Channel Handheld Scanner...,31.50,6.51,38.01
2,12-14440-08413,NaT,VA,Snap-on F4LA 3/8” Drive Speed Handle Crank Vin...,39.99,6.43,46.42
3,21-14417-16985,NaT,IN,Vintage Tool Lot Craftsman Ratchet Sockets Wre...,41.78,35.15,76.93
4,08-14436-02594,NaT,NY,Stanley Aladdin Lunch Box Cooler w/ Thermos 10...,51.00,13.25,64.25
5,24-14427-79252,NaT,PA,Vintage Craftsman 66577 Pry Bar USA Green Pati...,24.00,9.26,33.26

In [57]:
print(orders["sale_date"].head(10))

1    NaT
2    NaT
3    NaT
4    NaT
5    NaT
6    NaT
7    NaT
8    NaT
9    NaT
10   NaT
Name: sale_date, dtype: datetime64[ns]

In [59]:
orders = pd.read_csv("Documents/orders.csv", skiprows=1)
orders = orders[orders["Sales Record Number"].notna()].copy()

In [60]:
orders.columns = (
    orders.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [61]:
print(orders["sale_date"].head(10))

1     Mar-31-26
2     Mar-31-26
3     Mar-29-26
4     Mar-29-26
5     Mar-29-26
6     Mar-28-26
7     Mar-28-26
8     Mar-28-26
9     Mar-28-26
10    Mar-28-26
Name: sale_date, dtype: object

In [63]:
orders["sale_date"] = pd.to_datetime(
    orders["sale_date"],
    errors="coerce",
    dayfirst=False
)

In [64]:
print(orders["sale_date"].head(10))

1    2026-03-31
2    2026-03-31
3    2026-03-29
4    2026-03-29
5    2026-03-29
6    2026-03-28
7    2026-03-28
8    2026-03-28
9    2026-03-28
10   2026-03-28
Name: sale_date, dtype: datetime64[ns]

In [65]:
print(orders["sale_date"].isna().sum())

2

In [66]:
orders["gross_revenue"] = orders["sold_for"] + orders["shipping_and_handling"]
orders["sale_month"] = orders["sale_date"].dt.to_period("M").astype(str)

orders_clean = orders[
    [
        "order_number",
        "sale_date",
        "sale_month",
        "buyer_state",
        "item_title",
        "sold_for",
        "shipping_and_handling",
        "gross_revenue"
    ]
].copy()

orders_clean.head()

,order_number,sale_date,sale_month,buyer_state,item_title,sold_for,shipping_and_handling,gross_revenue
1,13-14439-25147,2026-03-31,2026-03,CA,RadioShack PRO-89 200 Channel Handheld Scanner...,$31.50,$6.51,$31.50$6.51
2,12-14440-08413,2026-03-31,2026-03,VA,Snap-on F4LA 3/8” Drive Speed Handle Crank Vin...,$39.99,$6.43,$39.99$6.43
3,21-14417-16985,2026-03-29,2026-03,IN,Vintage Tool Lot Craftsman Ratchet Sockets Wre...,$41.78,$35.15,$41.78$35.15
4,08-14436-02594,2026-03-29,2026-03,NY,Stanley Aladdin Lunch Box Cooler w/ Thermos 10...,$51.00,$13.25,$51.00$13.25
5,24-14427-79252,2026-03-29,2026-03,PA,Vintage Craftsman 66577 Pry Bar USA Green Pati...,$24.00,$9.26,$24.00$9.26

In [67]:
def clean_currency(series):
    return (
        series.astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
        .replace({"": None, "nan": None})
        .astype(float)
    )

In [68]:
orders["sold_for"] = clean_currency(orders["sold_for"])
orders["shipping_and_handling"] = clean_currency(orders["shipping_and_handling"])

In [69]:
orders["gross_revenue"] = orders["sold_for"] + orders["shipping_and_handling"]

In [70]:
orders[["sold_for", "shipping_and_handling", "gross_revenue"]].head()

   sold_for  shipping_and_handling  gross_revenue
1     31.50                   6.51          38.01
2     39.99                   6.43          46.42
3     41.78                  35.15          76.93
4     51.00                  13.25          64.25
5     24.00                   9.26          33.26

In [71]:
orders_clean = orders[
    [
        "order_number",
        "sale_date",
        "sale_month",
        "buyer_state",
        "item_title",
        "sold_for",
        "shipping_and_handling",
        "gross_revenue"
    ]
].copy()

orders_clean.to_csv("Documents/orders_clean.csv", index=False)

In [75]:
print(orders_clean.info())
orders_clean.select_dtypes(include=["number"]).describe()

<class 'pandas.core.frame.DataFrame'>
Index: 146 entries, 1 to 146
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_number           144 non-null    object
 1   sale_date              144 non-null    datetime64[ns]
 2   sale_month             146 non-null    object
 3   buyer_state            141 non-null    object
 4   item_title             143 non-null    object
 5   sold_for               144 non-null    float64
 6   shipping_and_handling  142 non-null    float64
 7   gross_revenue          142 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 10.3+ KB
None

         sold_for  shipping_and_handling  gross_revenue
count  144.000000             142.000000     142.000000
mean    38.245486               9.594155      47.977042
std     65.435245               8.407625      72.591236
min      8.000000               0.000000      13.070000
25%     17.000000               5.987500      24.200000
50%     24.000000               7.620000      32.145000
75%     39.990000               9.245000      48.835000
max    675.000000              87.560000     762.560000

In [76]:
print(orders_clean.isna().sum())

order_number             2
sale_date                2
sale_month               0
buyer_state              5
item_title               3
sold_for                 2
shipping_and_handling    4
gross_revenue            4
dtype: int64

In [73]:
print(orders_clean["buyer_state"].value_counts(dropna=False).head(15))

buyer_state
TX     15
CA     14
NY     10
PA      9
MO      8
IL      6
WI      5
IN      5
NC      5
NaN     5
CO      4
MN      4
AZ      4
FL      4
NV      3
Name: count, dtype: int64

In [77]:
orders_clean[orders_clean.isna().any(axis=1)]

,order_number,sale_date,sale_month,buyer_state,item_title,sold_for,shipping_and_handling,gross_revenue
8,26-14404-16793,2026-03-28,2026-03,TX,NaN,56.98,20.59,77.57
9,26-14404-16793,2026-03-28,2026-03,NaN,Estwing 16 oz Steel Claw Hammer USA One-Piece ...,19.99,NaN,NaN
10,26-14404-16793,2026-03-28,2026-03,NaN,Vintage Craftsman USA Screwdriver Lot Mixed Fl...,36.99,NaN,NaN
27,NaN,2026-03-18,2026-03,NaN,Vintage Craftsman Ignition Wrench Set Partial ...,18.00,0.00,18.00
145,record(s) downloaded,NaT,NaT,NaN,NaN,NaN,NaN,NaN
146,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN

In [82]:
# 1. Remove junk/footer rows
orders_clean = orders_clean[
    orders_clean["order_number"].notna() &
    (orders_clean["order_number"] != "record(s) downloaded")
].copy()

# 2. Drop rows missing required order/date fields
orders_clean = orders_clean.dropna(subset=["order_number", "sale_date"]).copy()

# 3. Fill missing shipping with 0 temporarily
orders_clean["shipping_and_handling"] = orders_clean["shipping_and_handling"].fillna(0)

# 4. Create allocated shipping per item within each order
orders_clean["shipping_allocated"] = (
    orders_clean.groupby("order_number")["shipping_and_handling"].transform("sum") /
    orders_clean.groupby("order_number")["order_number"].transform("count")
)

# 5. Replace shipping column with allocated shipping
orders_clean["shipping_and_handling"] = orders_clean["shipping_allocated"]

# 6. Drop helper column
orders_clean = orders_clean.drop(columns=["shipping_allocated"])

# 7. Drop rows with no item title (this removes the order summary row)
orders_clean = orders_clean.dropna(subset=["item_title"]).copy()

# 8. Fill missing buyer state
orders_clean["buyer_state"] = orders_clean["buyer_state"].fillna("Unknown")

# 9. Recalculate gross revenue
orders_clean["gross_revenue"] = (
    orders_clean["sold_for"] + orders_clean["shipping_and_handling"]
)

# 10. Check results
print(orders_clean.isna().sum())
print(orders_clean.shape)
orders_clean.head()

order_number             0
sale_date                0
sale_month               0
buyer_state              0
item_title               0
sold_for                 0
shipping_and_handling    0
gross_revenue            0
dtype: int64
(142, 8)

,order_number,sale_date,sale_month,buyer_state,item_title,sold_for,shipping_and_handling,gross_revenue
1,13-14439-25147,2026-03-31,2026-03,CA,RadioShack PRO-89 200 Channel Handheld Scanner...,31.50,6.51,38.01
2,12-14440-08413,2026-03-31,2026-03,VA,Snap-on F4LA 3/8” Drive Speed Handle Crank Vin...,39.99,6.43,46.42
3,21-14417-16985,2026-03-29,2026-03,IN,Vintage Tool Lot Craftsman Ratchet Sockets Wre...,41.78,35.15,76.93
4,08-14436-02594,2026-03-29,2026-03,NY,Stanley Aladdin Lunch Box Cooler w/ Thermos 10...,51.00,13.25,64.25
5,24-14427-79252,2026-03-29,2026-03,PA,Vintage Craftsman 66577 Pry Bar USA Green Pati...,24.00,9.26,33.26

In [ ]:
## Shipping charges were recorded inconsistently for some multi-item orders, so I allocated order-level shipping evenly across items to support item-level revenue analysis. ##

In [83]:
print(orders_clean.isna().sum())
print(orders_clean.shape)

order_number             0
sale_date                0
sale_month               0
buyer_state              0
item_title               0
sold_for                 0
shipping_and_handling    0
gross_revenue            0
dtype: int64
(142, 8)

In [84]:
orders_clean.to_csv("Documents/orders_final.csv", index=False)